### ISSUE TITLE
Add the LICENSE file to the sdist on PyPI

### ISSUE THREAD

**Issue by isuruf** [LucaCappelletti94/deflate_dict#1]
I'm trying to package deflate_dict for conda-forge and the LICENSE file is missing in the sdist.
I can workaround this, but it would be good to have.

Same issue in https://github.com/LucaCappelletti94/validate_version_code and https://github.com/LucaCappelletti94/support_developer

**Comment by LucaCappelletti94** [comment]
Published version with LICENSE on PyPi

**Comment by isuruf** [comment]
Thanks
